#!/usr/bin/env python2

from ledsignlib import *

nyanCat = [row.ljust(blockWidth, "B") for row in [
    "BBYYBBBBBBBYYBB",
    "BBYYYBBBBBYYYBB",
    "BYYRBYYYYYRBYYBGGGGGBBBBBRRRRRBB",
    "BRRYYYYYYYYYRRBGGGGGYYYYYRRRRRGG",
    "BRRYBYBYBYBYRRBBBBBBYYYYYBBBBBGG",
    "BBYYBBBBBBBYYBB",
    "BBBBYYYYYYYBBBB",
    "BBBBBBBBBBBBBBB"
]]

nyanCatUnited = []
for unit in range(numUnits):
    for row in nyanCat:
        nyanCatUnited.append(row[unit * unitWidth:unit * unitWidth + unitWidth])

nyanCat = nyanCatUnited

colours = {
    "B": 0b00, #0b00,
    "G": 0b01,
    "R": 0b10, #0b01,
    "Y": 0b11
}

byteArray = ""

for row in nyanCat:
    rowBytes = ""
    for i in range(0, len(row), pixelsPerByte):
        slice = row[i:i+4]
        byte = 0
        for char in slice:
            byte <<= 2
            byte |= colours[char]
        rowBytes += chr(byte)
    byteArray += rowBytes

send(graphicBlockPayload(byteArray))
send(pageContentPayload("<GA1> <CR>nyan~"))

run()
